/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SelecionarPerfilRouteImport } from './routes/selecionar-perfil'
import { Route as PassageiroRouteImport } from './routes/passageiro'
import { Route as ExcursionistaRouteImport } from './routes/excursionista'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as PassageiroIndexRouteImport } from './routes/passageiro.index'
import { Route as ExcursionistaIndexRouteImport } from './routes/excursionista.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as StaffSuporteRouteImport } from './routes/staff.suporte'
import { Route as StaffPerfilRouteImport } from './routes/staff.perfil'
import { Route as StaffPassageirosRouteImport } from './routes/staff.passageiros'
import { Route as StaffOnibusRouteImport } from './routes/staff.onibus'
import { Route as StaffFinanceiroRouteImport } from './routes/staff.financeiro'
import { Route as StaffEquipeRouteImport } from './routes/staff.equipe'
import { Route as StaffConfiguracoesRouteImport } from './routes/staff.configuracoes'
import { Route as StaffCheckinRouteImport } from './routes/staff.checkin'
import { Route as PassageiroTicketRouteImport } from './routes/passageiro.ticket'
import { Route as PassageiroSuporteRouteImport } from './routes/passageiro.suporte'
import { Route as PassageiroRegrasRouteImport } from './routes/passageiro.regras'
import { Route as PassageiroPoltronaRouteImport } from './routes/passageiro.poltrona'
import { Route as PassageiroPerfilRouteImport } from './routes/passageiro.perfil'
import { Route as PassageiroPagamentosRouteImport } from './routes/passageiro.pagamentos'
import { Route as PassageiroInformacoesRouteImport } from './routes/passageiro.informacoes'
import { Route as ExcursionistaPassageirosRouteImport } from './routes/excursionista.passageiros'
import { Route as ExcursionistaInfoRouteImport } from './routes/excursionista.info'
import { Route as ExcursionistaFinanceiroRouteImport } from './routes/excursionista.financeiro'
import { Route as ExcursionistaEditarRouteImport } from './routes/excursionista.editar'
import { Route as ExcursionistaCheckinRouteImport } from './routes/excursionista.checkin'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppPendentesRouteImport } from './routes/app.pendentes'
import { Route as AppPassageirosRouteImport } from './routes/app.passageiros'
import { Route as AppPagamentosConfigRouteImport } from './routes/app.pagamentos-config'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AppCustosRouteImport } from './routes/app.custos'
import { Route as StaffPassageiroIdRouteImport } from './routes/staff.passageiro.$id'
import { Route as PassageiroViagemIdRouteImport } from './routes/passageiro.viagem.$id'
import { Route as PassageiroReservaIdRouteImport } from './routes/passageiro.reserva.$id'
import { Route as InviteStaffTokenRouteImport } from './routes/invite.staff.$token'
import { Route as InvitePassageiroTokenRouteImport } from './routes/invite.passageiro.$token'
import { Route as ExcursionistaExcursaoIdRouteImport } from './routes/excursionista.excursao.$id'
import { Route as AppExcursaoNovaRouteImport } from './routes/app.excursao.nova'
import { Route as AppExcursaoIdRouteImport } from './routes/app.excursao.$id'
import { Route as AppExcursaoIdIndexRouteImport } from './routes/app.excursao.$id.index'
import { Route as AppExcursaoIdPontosRouteImport } from './routes/app.excursao.$id.pontos'
import { Route as AppExcursaoIdPassageirosRouteImport } from './routes/app.excursao.$id.passageiros'
import { Route as AppExcursaoIdOnibusRouteImport } from './routes/app.excursao.$id.onibus'
import { Route as AppExcursaoIdItensRouteImport } from './routes/app.excursao.$id.itens'
import { Route as AppExcursaoIdFinanceiroRouteImport } from './routes/app.excursao.$id.financeiro'
import { Route as AppExcursaoIdEquipeRouteImport } from './routes/app.excursao.$id.equipe'
import { Route as AppExcursaoIdCheckinRouteImport } from './routes/app.excursao.$id.checkin'
import { Route as AppExcursaoIdOnibusOnibusIdRouteImport } from './routes/app.excursao.$id.onibus.$onibusId'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecionarPerfilRoute = SelecionarPerfilRouteImport.update({
  id: '/selecionar-perfil',
  path: '/selecionar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroRoute = PassageiroRouteImport.update({
  id: '/passageiro',
  path: '/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcursionistaRoute = ExcursionistaRouteImport.update({
  id: '/excursionista',
  path: '/excursionista',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const PassageiroIndexRoute = PassageiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PassageiroRoute,
} as any)
const ExcursionistaIndexRoute = ExcursionistaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const StaffSuporteRoute = StaffSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPerfilRoute = StaffPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPassageirosRoute = StaffPassageirosRouteImport.update({
  id: '/passageiros',
  path: '/passageiros',
  getParentRoute: () => StaffRoute,
} as any)
const StaffOnibusRoute = StaffOnibusRouteImport.update({
  id: '/onibus',
  path: '/onibus',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFinanceiroRoute = StaffFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => StaffRoute,
} as any)
const StaffEquipeRoute = StaffEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => StaffRoute,
} as any)
const StaffConfiguracoesRoute = StaffConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCheckinRoute = StaffCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => StaffRoute,
} as any)
const PassageiroTicketRoute = PassageiroTicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroSuporteRoute = PassageiroSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroRegrasRoute = PassageiroRegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroPoltronaRoute = PassageiroPoltronaRouteImport.update({
  id: '/poltrona',
  path: '/poltrona',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroPerfilRoute = PassageiroPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroPagamentosRoute = PassageiroPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroInformacoesRoute = PassageiroInformacoesRouteImport.update({
  id: '/informacoes',
  path: '/informacoes',
  getParentRoute: () => PassageiroRoute,
} as any)
const ExcursionistaPassageirosRoute =
  ExcursionistaPassageirosRouteImport.update({
    id: '/passageiros',
    path: '/passageiros',
    getParentRoute: () => ExcursionistaRoute,
  } as any)
const ExcursionistaInfoRoute = ExcursionistaInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const ExcursionistaFinanceiroRoute = ExcursionistaFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const ExcursionistaEditarRoute = ExcursionistaEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const ExcursionistaCheckinRoute = ExcursionistaCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPendentesRoute = AppPendentesRouteImport.update({
  id: '/pendentes',
  path: '/pendentes',
  getParentRoute: () => AppRoute,
} as any)
const AppPassageirosRoute = AppPassageirosRouteImport.update({
  id: '/passageiros',
  path: '/passageiros',
  getParentRoute: () => AppRoute,
} as any)
const AppPagamentosConfigRoute = AppPagamentosConfigRouteImport.update({
  id: '/pagamentos-config',
  path: '/pagamentos-config',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppCustosRoute = AppCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AppRoute,
} as any)
const StaffPassageiroIdRoute = StaffPassageiroIdRouteImport.update({
  id: '/passageiro/$id',
  path: '/passageiro/$id',
  getParentRoute: () => StaffRoute,
} as any)
const PassageiroViagemIdRoute = PassageiroViagemIdRouteImport.update({
  id: '/viagem/$id',
  path: '/viagem/$id',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroReservaIdRoute = PassageiroReservaIdRouteImport.update({
  id: '/reserva/$id',
  path: '/reserva/$id',
  getParentRoute: () => PassageiroRoute,
} as any)
const InviteStaffTokenRoute = InviteStaffTokenRouteImport.update({
  id: '/invite/staff/$token',
  path: '/invite/staff/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitePassageiroTokenRoute = InvitePassageiroTokenRouteImport.update({
  id: '/invite/passageiro/$token',
  path: '/invite/passageiro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcursionistaExcursaoIdRoute = ExcursionistaExcursaoIdRouteImport.update({
  id: '/excursao/$id',
  path: '/excursao/$id',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const AppExcursaoNovaRoute = AppExcursaoNovaRouteImport.update({
  id: '/excursao/nova',
  path: '/excursao/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppExcursaoIdRoute = AppExcursaoIdRouteImport.update({
  id: '/excursao/$id',
  path: '/excursao/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppExcursaoIdIndexRoute = AppExcursaoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)
const AppExcursaoIdPontosRoute = AppExcursaoIdPontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)
const AppExcursaoIdPassageirosRoute =
  AppExcursaoIdPassageirosRouteImport.update({
    id: '/passageiros',
    path: '/passageiros',
    getParentRoute: () => AppExcursaoIdRoute,
  } as any)
const AppExcursaoIdOnibusRoute = AppExcursaoIdOnibusRouteImport.update({
  id: '/onibus',
  path: '/onibus',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)
const AppExcursaoIdItensRoute = AppExcursaoIdItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)
const AppExcursaoIdFinanceiroRoute = AppExcursaoIdFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)
const AppExcursaoIdEquipeRoute = AppExcursaoIdEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)
const AppExcursaoIdCheckinRoute = AppExcursaoIdCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)
const AppExcursaoIdOnibusOnibusIdRoute =
  AppExcursaoIdOnibusOnibusIdRouteImport.update({
    id: '/$onibusId',
    path: '/$onibusId',
    getParentRoute: () => AppExcursaoIdOnibusRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/excursionista': typeof ExcursionistaRouteWithChildren
  '/passageiro': typeof PassageiroRouteWithChildren
  '/selecionar-perfil': typeof SelecionarPerfilRoute
  '/staff': typeof StaffRouteWithChildren
  '/app/custos': typeof AppCustosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/pagamentos-config': typeof AppPagamentosConfigRoute
  '/app/passageiros': typeof AppPassageirosRoute
  '/app/pendentes': typeof AppPendentesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/excursionista/checkin': typeof ExcursionistaCheckinRoute
  '/excursionista/editar': typeof ExcursionistaEditarRoute
  '/excursionista/financeiro': typeof ExcursionistaFinanceiroRoute
  '/excursionista/info': typeof ExcursionistaInfoRoute
  '/excursionista/passageiros': typeof ExcursionistaPassageirosRoute
  '/passageiro/informacoes': typeof PassageiroInformacoesRoute
  '/passageiro/pagamentos': typeof PassageiroPagamentosRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/passageiro/poltrona': typeof PassageiroPoltronaRoute
  '/passageiro/regras': typeof PassageiroRegrasRoute
  '/passageiro/suporte': typeof PassageiroSuporteRoute
  '/passageiro/ticket': typeof PassageiroTicketRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/configuracoes': typeof StaffConfiguracoesRoute
  '/staff/equipe': typeof StaffEquipeRoute
  '/staff/financeiro': typeof StaffFinanceiroRoute
  '/staff/onibus': typeof StaffOnibusRoute
  '/staff/passageiros': typeof StaffPassageirosRoute
  '/staff/perfil': typeof StaffPerfilRoute
  '/staff/suporte': typeof StaffSuporteRoute
  '/app/': typeof AppIndexRoute
  '/excursionista/': typeof ExcursionistaIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/app/excursao/$id': typeof AppExcursaoIdRouteWithChildren
  '/app/excursao/nova': typeof AppExcursaoNovaRoute
  '/excursionista/excursao/$id': typeof ExcursionistaExcursaoIdRoute
  '/invite/passageiro/$token': typeof InvitePassageiroTokenRoute
  '/invite/staff/$token': typeof InviteStaffTokenRoute
  '/passageiro/reserva/$id': typeof PassageiroReservaIdRoute
  '/passageiro/viagem/$id': typeof PassageiroViagemIdRoute
  '/staff/passageiro/$id': typeof StaffPassageiroIdRoute
  '/app/excursao/$id/checkin': typeof AppExcursaoIdCheckinRoute
  '/app/excursao/$id/equipe': typeof AppExcursaoIdEquipeRoute
  '/app/excursao/$id/financeiro': typeof AppExcursaoIdFinanceiroRoute
  '/app/excursao/$id/itens': typeof AppExcursaoIdItensRoute
  '/app/excursao/$id/onibus': typeof AppExcursaoIdOnibusRouteWithChildren
  '/app/excursao/$id/passageiros': typeof AppExcursaoIdPassageirosRoute
  '/app/excursao/$id/pontos': typeof AppExcursaoIdPontosRoute
  '/app/excursao/$id/': typeof AppExcursaoIdIndexRoute
  '/app/excursao/$id/onibus/$onibusId': typeof AppExcursaoIdOnibusOnibusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/selecionar-perfil': typeof SelecionarPerfilRoute
  '/app/custos': typeof AppCustosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/pagamentos-config': typeof AppPagamentosConfigRoute
  '/app/passageiros': typeof AppPassageirosRoute
  '/app/pendentes': typeof AppPendentesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/excursionista/checkin': typeof ExcursionistaCheckinRoute
  '/excursionista/editar': typeof ExcursionistaEditarRoute
  '/excursionista/financeiro': typeof ExcursionistaFinanceiroRoute
  '/excursionista/info': typeof ExcursionistaInfoRoute
  '/excursionista/passageiros': typeof ExcursionistaPassageirosRoute
  '/passageiro/informacoes': typeof PassageiroInformacoesRoute
  '/passageiro/pagamentos': typeof PassageiroPagamentosRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/passageiro/poltrona': typeof PassageiroPoltronaRoute
  '/passageiro/regras': typeof PassageiroRegrasRoute
  '/passageiro/suporte': typeof PassageiroSuporteRoute
  '/passageiro/ticket': typeof PassageiroTicketRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/configuracoes': typeof StaffConfiguracoesRoute
  '/staff/equipe': typeof StaffEquipeRoute
  '/staff/financeiro': typeof StaffFinanceiroRoute
  '/staff/onibus': typeof StaffOnibusRoute
  '/staff/passageiros': typeof StaffPassageirosRoute
  '/staff/perfil': typeof StaffPerfilRoute
  '/staff/suporte': typeof StaffSuporteRoute
  '/app': typeof AppIndexRoute
  '/excursionista': typeof ExcursionistaIndexRoute
  '/passageiro': typeof PassageiroIndexRoute
  '/staff': typeof StaffIndexRoute
  '/app/excursao/nova': typeof AppExcursaoNovaRoute
  '/excursionista/excursao/$id': typeof ExcursionistaExcursaoIdRoute
  '/invite/passageiro/$token': typeof InvitePassageiroTokenRoute
  '/invite/staff/$token': typeof InviteStaffTokenRoute
  '/passageiro/reserva/$id': typeof PassageiroReservaIdRoute
  '/passageiro/viagem/$id': typeof PassageiroViagemIdRoute
  '/staff/passageiro/$id': typeof StaffPassageiroIdRoute
  '/app/excursao/$id/checkin': typeof AppExcursaoIdCheckinRoute
  '/app/excursao/$id/equipe': typeof AppExcursaoIdEquipeRoute
  '/app/excursao/$id/financeiro': typeof AppExcursaoIdFinanceiroRoute
  '/app/excursao/$id/itens': typeof AppExcursaoIdItensRoute
  '/app/excursao/$id/onibus': typeof AppExcursaoIdOnibusRouteWithChildren
  '/app/excursao/$id/passageiros': typeof AppExcursaoIdPassageirosRoute
  '/app/excursao/$id/pontos': typeof AppExcursaoIdPontosRoute
  '/app/excursao/$id': typeof AppExcursaoIdIndexRoute
  '/app/excursao/$id/onibus/$onibusId': typeof AppExcursaoIdOnibusOnibusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/excursionista': typeof ExcursionistaRouteWithChildren
  '/passageiro': typeof PassageiroRouteWithChildren
  '/selecionar-perfil': typeof SelecionarPerfilRoute
  '/staff': typeof StaffRouteWithChildren
  '/app/custos': typeof AppCustosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/pagamentos-config': typeof AppPagamentosConfigRoute
  '/app/passageiros': typeof AppPassageirosRoute
  '/app/pendentes': typeof AppPendentesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/excursionista/checkin': typeof ExcursionistaCheckinRoute
  '/excursionista/editar': typeof ExcursionistaEditarRoute
  '/excursionista/financeiro': typeof ExcursionistaFinanceiroRoute
  '/excursionista/info': typeof ExcursionistaInfoRoute
  '/excursionista/passageiros': typeof ExcursionistaPassageirosRoute
  '/passageiro/informacoes': typeof PassageiroInformacoesRoute
  '/passageiro/pagamentos': typeof PassageiroPagamentosRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/passageiro/poltrona': typeof PassageiroPoltronaRoute
  '/passageiro/regras': typeof PassageiroRegrasRoute
  '/passageiro/suporte': typeof PassageiroSuporteRoute
  '/passageiro/ticket': typeof PassageiroTicketRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/configuracoes': typeof StaffConfiguracoesRoute
  '/staff/equipe': typeof StaffEquipeRoute
  '/staff/financeiro': typeof StaffFinanceiroRoute
  '/staff/onibus': typeof StaffOnibusRoute
  '/staff/passageiros': typeof StaffPassageirosRoute
  '/staff/perfil': typeof StaffPerfilRoute
  '/staff/suporte': typeof StaffSuporteRoute
  '/app/': typeof AppIndexRoute
  '/excursionista/': typeof ExcursionistaIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/app/excursao/$id': typeof AppExcursaoIdRouteWithChildren
  '/app/excursao/nova': typeof AppExcursaoNovaRoute
  '/excursionista/excursao/$id': typeof ExcursionistaExcursaoIdRoute
  '/invite/passageiro/$token': typeof InvitePassageiroTokenRoute
  '/invite/staff/$token': typeof InviteStaffTokenRoute
  '/passageiro/reserva/$id': typeof PassageiroReservaIdRoute
  '/passageiro/viagem/$id': typeof PassageiroViagemIdRoute
  '/staff/passageiro/$id': typeof StaffPassageiroIdRoute
  '/app/excursao/$id/checkin': typeof AppExcursaoIdCheckinRoute
  '/app/excursao/$id/equipe': typeof AppExcursaoIdEquipeRoute
  '/app/excursao/$id/financeiro': typeof AppExcursaoIdFinanceiroRoute
  '/app/excursao/$id/itens': typeof AppExcursaoIdItensRoute
  '/app/excursao/$id/onibus': typeof AppExcursaoIdOnibusRouteWithChildren
  '/app/excursao/$id/passageiros': typeof AppExcursaoIdPassageirosRoute
  '/app/excursao/$id/pontos': typeof AppExcursaoIdPontosRoute
  '/app/excursao/$id/': typeof AppExcursaoIdIndexRoute
  '/app/excursao/$id/onibus/$onibusId': typeof AppExcursaoIdOnibusOnibusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/excursionista'
    | '/passageiro'
    | '/selecionar-perfil'
    | '/staff'
    | '/app/custos'
    | '/app/historico'
    | '/app/pagamentos-config'
    | '/app/passageiros'
    | '/app/pendentes'
    | '/app/perfil'
    | '/app/relatorios'
    | '/excursionista/checkin'
    | '/excursionista/editar'
    | '/excursionista/financeiro'
    | '/excursionista/info'
    | '/excursionista/passageiros'
    | '/passageiro/informacoes'
    | '/passageiro/pagamentos'
    | '/passageiro/perfil'
    | '/passageiro/poltrona'
    | '/passageiro/regras'
    | '/passageiro/suporte'
    | '/passageiro/ticket'
    | '/staff/checkin'
    | '/staff/configuracoes'
    | '/staff/equipe'
    | '/staff/financeiro'
    | '/staff/onibus'
    | '/staff/passageiros'
    | '/staff/perfil'
    | '/staff/suporte'
    | '/app/'
    | '/excursionista/'
    | '/passageiro/'
    | '/staff/'
    | '/app/excursao/$id'
    | '/app/excursao/nova'
    | '/excursionista/excursao/$id'
    | '/invite/passageiro/$token'
    | '/invite/staff/$token'
    | '/passageiro/reserva/$id'
    | '/passageiro/viagem/$id'
    | '/staff/passageiro/$id'
    | '/app/excursao/$id/checkin'
    | '/app/excursao/$id/equipe'
    | '/app/excursao/$id/financeiro'
    | '/app/excursao/$id/itens'
    | '/app/excursao/$id/onibus'
    | '/app/excursao/$id/passageiros'
    | '/app/excursao/$id/pontos'
    | '/app/excursao/$id/'
    | '/app/excursao/$id/onibus/$onibusId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/selecionar-perfil'
    | '/app/custos'
    | '/app/historico'
    | '/app/pagamentos-config'
    | '/app/passageiros'
    | '/app/pendentes'
    | '/app/perfil'
    | '/app/relatorios'
    | '/excursionista/checkin'
    | '/excursionista/editar'
    | '/excursionista/financeiro'
    | '/excursionista/info'
    | '/excursionista/passageiros'
    | '/passageiro/informacoes'
    | '/passageiro/pagamentos'
    | '/passageiro/perfil'
    | '/passageiro/poltrona'
    | '/passageiro/regras'
    | '/passageiro/suporte'
    | '/passageiro/ticket'
    | '/staff/checkin'
    | '/staff/configuracoes'
    | '/staff/equipe'
    | '/staff/financeiro'
    | '/staff/onibus'
    | '/staff/passageiros'
    | '/staff/perfil'
    | '/staff/suporte'
    | '/app'
    | '/excursionista'
    | '/passageiro'
    | '/staff'
    | '/app/excursao/nova'
    | '/excursionista/excursao/$id'
    | '/invite/passageiro/$token'
    | '/invite/staff/$token'
    | '/passageiro/reserva/$id'
    | '/passageiro/viagem/$id'
    | '/staff/passageiro/$id'
    | '/app/excursao/$id/checkin'
    | '/app/excursao/$id/equipe'
    | '/app/excursao/$id/financeiro'
    | '/app/excursao/$id/itens'
    | '/app/excursao/$id/onibus'
    | '/app/excursao/$id/passageiros'
    | '/app/excursao/$id/pontos'
    | '/app/excursao/$id'
    | '/app/excursao/$id/onibus/$onibusId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/excursionista'
    | '/passageiro'
    | '/selecionar-perfil'
    | '/staff'
    | '/app/custos'
    | '/app/historico'
    | '/app/pagamentos-config'
    | '/app/passageiros'
    | '/app/pendentes'
    | '/app/perfil'
    | '/app/relatorios'
    | '/excursionista/checkin'
    | '/excursionista/editar'
    | '/excursionista/financeiro'
    | '/excursionista/info'
    | '/excursionista/passageiros'
    | '/passageiro/informacoes'
    | '/passageiro/pagamentos'
    | '/passageiro/perfil'
    | '/passageiro/poltrona'
    | '/passageiro/regras'
    | '/passageiro/suporte'
    | '/passageiro/ticket'
    | '/staff/checkin'
    | '/staff/configuracoes'
    | '/staff/equipe'
    | '/staff/financeiro'
    | '/staff/onibus'
    | '/staff/passageiros'
    | '/staff/perfil'
    | '/staff/suporte'
    | '/app/'
    | '/excursionista/'
    | '/passageiro/'
    | '/staff/'
    | '/app/excursao/$id'
    | '/app/excursao/nova'
    | '/excursionista/excursao/$id'
    | '/invite/passageiro/$token'
    | '/invite/staff/$token'
    | '/passageiro/reserva/$id'
    | '/passageiro/viagem/$id'
    | '/staff/passageiro/$id'
    | '/app/excursao/$id/checkin'
    | '/app/excursao/$id/equipe'
    | '/app/excursao/$id/financeiro'
    | '/app/excursao/$id/itens'
    | '/app/excursao/$id/onibus'
    | '/app/excursao/$id/passageiros'
    | '/app/excursao/$id/pontos'
    | '/app/excursao/$id/'
    | '/app/excursao/$id/onibus/$onibusId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExcursionistaRoute: typeof ExcursionistaRouteWithChildren
  PassageiroRoute: typeof PassageiroRouteWithChildren
  SelecionarPerfilRoute: typeof SelecionarPerfilRoute
  StaffRoute: typeof StaffRouteWithChildren
  InvitePassageiroTokenRoute: typeof InvitePassageiroTokenRoute
  InviteStaffTokenRoute: typeof InviteStaffTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecionar-perfil': {
      id: '/selecionar-perfil'
      path: '/selecionar-perfil'
      fullPath: '/selecionar-perfil'
      preLoaderRoute: typeof SelecionarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro': {
      id: '/passageiro'
      path: '/passageiro'
      fullPath: '/passageiro'
      preLoaderRoute: typeof PassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excursionista': {
      id: '/excursionista'
      path: '/excursionista'
      fullPath: '/excursionista'
      preLoaderRoute: typeof ExcursionistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/passageiro/': {
      id: '/passageiro/'
      path: '/'
      fullPath: '/passageiro/'
      preLoaderRoute: typeof PassageiroIndexRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/excursionista/': {
      id: '/excursionista/'
      path: '/'
      fullPath: '/excursionista/'
      preLoaderRoute: typeof ExcursionistaIndexRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/staff/suporte': {
      id: '/staff/suporte'
      path: '/suporte'
      fullPath: '/staff/suporte'
      preLoaderRoute: typeof StaffSuporteRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/perfil': {
      id: '/staff/perfil'
      path: '/perfil'
      fullPath: '/staff/perfil'
      preLoaderRoute: typeof StaffPerfilRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/passageiros': {
      id: '/staff/passageiros'
      path: '/passageiros'
      fullPath: '/staff/passageiros'
      preLoaderRoute: typeof StaffPassageirosRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/onibus': {
      id: '/staff/onibus'
      path: '/onibus'
      fullPath: '/staff/onibus'
      preLoaderRoute: typeof StaffOnibusRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/financeiro': {
      id: '/staff/financeiro'
      path: '/financeiro'
      fullPath: '/staff/financeiro'
      preLoaderRoute: typeof StaffFinanceiroRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/equipe': {
      id: '/staff/equipe'
      path: '/equipe'
      fullPath: '/staff/equipe'
      preLoaderRoute: typeof StaffEquipeRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/configuracoes': {
      id: '/staff/configuracoes'
      path: '/configuracoes'
      fullPath: '/staff/configuracoes'
      preLoaderRoute: typeof StaffConfiguracoesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/checkin': {
      id: '/staff/checkin'
      path: '/checkin'
      fullPath: '/staff/checkin'
      preLoaderRoute: typeof StaffCheckinRouteImport
      parentRoute: typeof StaffRoute
    }
    '/passageiro/ticket': {
      id: '/passageiro/ticket'
      path: '/ticket'
      fullPath: '/passageiro/ticket'
      preLoaderRoute: typeof PassageiroTicketRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/suporte': {
      id: '/passageiro/suporte'
      path: '/suporte'
      fullPath: '/passageiro/suporte'
      preLoaderRoute: typeof PassageiroSuporteRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/regras': {
      id: '/passageiro/regras'
      path: '/regras'
      fullPath: '/passageiro/regras'
      preLoaderRoute: typeof PassageiroRegrasRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/poltrona': {
      id: '/passageiro/poltrona'
      path: '/poltrona'
      fullPath: '/passageiro/poltrona'
      preLoaderRoute: typeof PassageiroPoltronaRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/perfil': {
      id: '/passageiro/perfil'
      path: '/perfil'
      fullPath: '/passageiro/perfil'
      preLoaderRoute: typeof PassageiroPerfilRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/pagamentos': {
      id: '/passageiro/pagamentos'
      path: '/pagamentos'
      fullPath: '/passageiro/pagamentos'
      preLoaderRoute: typeof PassageiroPagamentosRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/informacoes': {
      id: '/passageiro/informacoes'
      path: '/informacoes'
      fullPath: '/passageiro/informacoes'
      preLoaderRoute: typeof PassageiroInformacoesRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/excursionista/passageiros': {
      id: '/excursionista/passageiros'
      path: '/passageiros'
      fullPath: '/excursionista/passageiros'
      preLoaderRoute: typeof ExcursionistaPassageirosRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/excursionista/info': {
      id: '/excursionista/info'
      path: '/info'
      fullPath: '/excursionista/info'
      preLoaderRoute: typeof ExcursionistaInfoRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/excursionista/financeiro': {
      id: '/excursionista/financeiro'
      path: '/financeiro'
      fullPath: '/excursionista/financeiro'
      preLoaderRoute: typeof ExcursionistaFinanceiroRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/excursionista/editar': {
      id: '/excursionista/editar'
      path: '/editar'
      fullPath: '/excursionista/editar'
      preLoaderRoute: typeof ExcursionistaEditarRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/excursionista/checkin': {
      id: '/excursionista/checkin'
      path: '/checkin'
      fullPath: '/excursionista/checkin'
      preLoaderRoute: typeof ExcursionistaCheckinRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pendentes': {
      id: '/app/pendentes'
      path: '/pendentes'
      fullPath: '/app/pendentes'
      preLoaderRoute: typeof AppPendentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/passageiros': {
      id: '/app/passageiros'
      path: '/passageiros'
      fullPath: '/app/passageiros'
      preLoaderRoute: typeof AppPassageirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pagamentos-config': {
      id: '/app/pagamentos-config'
      path: '/pagamentos-config'
      fullPath: '/app/pagamentos-config'
      preLoaderRoute: typeof AppPagamentosConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/custos': {
      id: '/app/custos'
      path: '/custos'
      fullPath: '/app/custos'
      preLoaderRoute: typeof AppCustosRouteImport
      parentRoute: typeof AppRoute
    }
    '/staff/passageiro/$id': {
      id: '/staff/passageiro/$id'
      path: '/passageiro/$id'
      fullPath: '/staff/passageiro/$id'
      preLoaderRoute: typeof StaffPassageiroIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/passageiro/viagem/$id': {
      id: '/passageiro/viagem/$id'
      path: '/viagem/$id'
      fullPath: '/passageiro/viagem/$id'
      preLoaderRoute: typeof PassageiroViagemIdRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/reserva/$id': {
      id: '/passageiro/reserva/$id'
      path: '/reserva/$id'
      fullPath: '/passageiro/reserva/$id'
      preLoaderRoute: typeof PassageiroReservaIdRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/invite/staff/$token': {
      id: '/invite/staff/$token'
      path: '/invite/staff/$token'
      fullPath: '/invite/staff/$token'
      preLoaderRoute: typeof InviteStaffTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/passageiro/$token': {
      id: '/invite/passageiro/$token'
      path: '/invite/passageiro/$token'
      fullPath: '/invite/passageiro/$token'
      preLoaderRoute: typeof InvitePassageiroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excursionista/excursao/$id': {
      id: '/excursionista/excursao/$id'
      path: '/excursao/$id'
      fullPath: '/excursionista/excursao/$id'
      preLoaderRoute: typeof ExcursionistaExcursaoIdRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/app/excursao/nova': {
      id: '/app/excursao/nova'
      path: '/excursao/nova'
      fullPath: '/app/excursao/nova'
      preLoaderRoute: typeof AppExcursaoNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/excursao/$id': {
      id: '/app/excursao/$id'
      path: '/excursao/$id'
      fullPath: '/app/excursao/$id'
      preLoaderRoute: typeof AppExcursaoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/excursao/$id/': {
      id: '/app/excursao/$id/'
      path: '/'
      fullPath: '/app/excursao/$id/'
      preLoaderRoute: typeof AppExcursaoIdIndexRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/pontos': {
      id: '/app/excursao/$id/pontos'
      path: '/pontos'
      fullPath: '/app/excursao/$id/pontos'
      preLoaderRoute: typeof AppExcursaoIdPontosRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/passageiros': {
      id: '/app/excursao/$id/passageiros'
      path: '/passageiros'
      fullPath: '/app/excursao/$id/passageiros'
      preLoaderRoute: typeof AppExcursaoIdPassageirosRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/onibus': {
      id: '/app/excursao/$id/onibus'
      path: '/onibus'
      fullPath: '/app/excursao/$id/onibus'
      preLoaderRoute: typeof AppExcursaoIdOnibusRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/itens': {
      id: '/app/excursao/$id/itens'
      path: '/itens'
      fullPath: '/app/excursao/$id/itens'
      preLoaderRoute: typeof AppExcursaoIdItensRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/financeiro': {
      id: '/app/excursao/$id/financeiro'
      path: '/financeiro'
      fullPath: '/app/excursao/$id/financeiro'
      preLoaderRoute: typeof AppExcursaoIdFinanceiroRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/equipe': {
      id: '/app/excursao/$id/equipe'
      path: '/equipe'
      fullPath: '/app/excursao/$id/equipe'
      preLoaderRoute: typeof AppExcursaoIdEquipeRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/checkin': {
      id: '/app/excursao/$id/checkin'
      path: '/checkin'
      fullPath: '/app/excursao/$id/checkin'
      preLoaderRoute: typeof AppExcursaoIdCheckinRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/onibus/$onibusId': {
      id: '/app/excursao/$id/onibus/$onibusId'
      path: '/$onibusId'
      fullPath: '/app/excursao/$id/onibus/$onibusId'
      preLoaderRoute: typeof AppExcursaoIdOnibusOnibusIdRouteImport
      parentRoute: typeof AppExcursaoIdOnibusRoute
    }
  }
}

interface AppExcursaoIdOnibusRouteChildren {
  AppExcursaoIdOnibusOnibusIdRoute: typeof AppExcursaoIdOnibusOnibusIdRoute
}

const AppExcursaoIdOnibusRouteChildren: AppExcursaoIdOnibusRouteChildren = {
  AppExcursaoIdOnibusOnibusIdRoute: AppExcursaoIdOnibusOnibusIdRoute,
}

const AppExcursaoIdOnibusRouteWithChildren =
  AppExcursaoIdOnibusRoute._addFileChildren(AppExcursaoIdOnibusRouteChildren)

interface AppExcursaoIdRouteChildren {
  AppExcursaoIdCheckinRoute: typeof AppExcursaoIdCheckinRoute
  AppExcursaoIdEquipeRoute: typeof AppExcursaoIdEquipeRoute
  AppExcursaoIdFinanceiroRoute: typeof AppExcursaoIdFinanceiroRoute
  AppExcursaoIdItensRoute: typeof AppExcursaoIdItensRoute
  AppExcursaoIdOnibusRoute: typeof AppExcursaoIdOnibusRouteWithChildren
  AppExcursaoIdPassageirosRoute: typeof AppExcursaoIdPassageirosRoute
  AppExcursaoIdPontosRoute: typeof AppExcursaoIdPontosRoute
  AppExcursaoIdIndexRoute: typeof AppExcursaoIdIndexRoute
}

const AppExcursaoIdRouteChildren: AppExcursaoIdRouteChildren = {
  AppExcursaoIdCheckinRoute: AppExcursaoIdCheckinRoute,
  AppExcursaoIdEquipeRoute: AppExcursaoIdEquipeRoute,
  AppExcursaoIdFinanceiroRoute: AppExcursaoIdFinanceiroRoute,
  AppExcursaoIdItensRoute: AppExcursaoIdItensRoute,
  AppExcursaoIdOnibusRoute: AppExcursaoIdOnibusRouteWithChildren,
  AppExcursaoIdPassageirosRoute: AppExcursaoIdPassageirosRoute,
  AppExcursaoIdPontosRoute: AppExcursaoIdPontosRoute,
  AppExcursaoIdIndexRoute: AppExcursaoIdIndexRoute,
}

const AppExcursaoIdRouteWithChildren = AppExcursaoIdRoute._addFileChildren(
  AppExcursaoIdRouteChildren,
)

interface AppRouteChildren {
  AppCustosRoute: typeof AppCustosRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppPagamentosConfigRoute: typeof AppPagamentosConfigRoute
  AppPassageirosRoute: typeof AppPassageirosRoute
  AppPendentesRoute: typeof AppPendentesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExcursaoIdRoute: typeof AppExcursaoIdRouteWithChildren
  AppExcursaoNovaRoute: typeof AppExcursaoNovaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustosRoute: AppCustosRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppPagamentosConfigRoute: AppPagamentosConfigRoute,
  AppPassageirosRoute: AppPassageirosRoute,
  AppPendentesRoute: AppPendentesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
  AppExcursaoIdRoute: AppExcursaoIdRouteWithChildren,
  AppExcursaoNovaRoute: AppExcursaoNovaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ExcursionistaRouteChildren {
  ExcursionistaCheckinRoute: typeof ExcursionistaCheckinRoute
  ExcursionistaEditarRoute: typeof ExcursionistaEditarRoute
  ExcursionistaFinanceiroRoute: typeof ExcursionistaFinanceiroRoute
  ExcursionistaInfoRoute: typeof ExcursionistaInfoRoute
  ExcursionistaPassageirosRoute: typeof ExcursionistaPassageirosRoute
  ExcursionistaIndexRoute: typeof ExcursionistaIndexRoute
  ExcursionistaExcursaoIdRoute: typeof ExcursionistaExcursaoIdRoute
}

const ExcursionistaRouteChildren: ExcursionistaRouteChildren = {
  ExcursionistaCheckinRoute: ExcursionistaCheckinRoute,
  ExcursionistaEditarRoute: ExcursionistaEditarRoute,
  ExcursionistaFinanceiroRoute: ExcursionistaFinanceiroRoute,
  ExcursionistaInfoRoute: ExcursionistaInfoRoute,
  ExcursionistaPassageirosRoute: ExcursionistaPassageirosRoute,
  ExcursionistaIndexRoute: ExcursionistaIndexRoute,
  ExcursionistaExcursaoIdRoute: ExcursionistaExcursaoIdRoute,
}

const ExcursionistaRouteWithChildren = ExcursionistaRoute._addFileChildren(
  ExcursionistaRouteChildren,
)

interface PassageiroRouteChildren {
  PassageiroInformacoesRoute: typeof PassageiroInformacoesRoute
  PassageiroPagamentosRoute: typeof PassageiroPagamentosRoute
  PassageiroPerfilRoute: typeof PassageiroPerfilRoute
  PassageiroPoltronaRoute: typeof PassageiroPoltronaRoute
  PassageiroRegrasRoute: typeof PassageiroRegrasRoute
  PassageiroSuporteRoute: typeof PassageiroSuporteRoute
  PassageiroTicketRoute: typeof PassageiroTicketRoute
  PassageiroIndexRoute: typeof PassageiroIndexRoute
  PassageiroReservaIdRoute: typeof PassageiroReservaIdRoute
  PassageiroViagemIdRoute: typeof PassageiroViagemIdRoute
}

const PassageiroRouteChildren: PassageiroRouteChildren = {
  PassageiroInformacoesRoute: PassageiroInformacoesRoute,
  PassageiroPagamentosRoute: PassageiroPagamentosRoute,
  PassageiroPerfilRoute: PassageiroPerfilRoute,
  PassageiroPoltronaRoute: PassageiroPoltronaRoute,
  PassageiroRegrasRoute: PassageiroRegrasRoute,
  PassageiroSuporteRoute: PassageiroSuporteRoute,
  PassageiroTicketRoute: PassageiroTicketRoute,
  PassageiroIndexRoute: PassageiroIndexRoute,
  PassageiroReservaIdRoute: PassageiroReservaIdRoute,
  PassageiroViagemIdRoute: PassageiroViagemIdRoute,
}

const PassageiroRouteWithChildren = PassageiroRoute._addFileChildren(
  PassageiroRouteChildren,
)

interface StaffRouteChildren {
  StaffCheckinRoute: typeof StaffCheckinRoute
  StaffConfiguracoesRoute: typeof StaffConfiguracoesRoute
  StaffEquipeRoute: typeof StaffEquipeRoute
  StaffFinanceiroRoute: typeof StaffFinanceiroRoute
  StaffOnibusRoute: typeof StaffOnibusRoute
  StaffPassageirosRoute: typeof StaffPassageirosRoute
  StaffPerfilRoute: typeof StaffPerfilRoute
  StaffSuporteRoute: typeof StaffSuporteRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffPassageiroIdRoute: typeof StaffPassageiroIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCheckinRoute: StaffCheckinRoute,
  StaffConfiguracoesRoute: StaffConfiguracoesRoute,
  StaffEquipeRoute: StaffEquipeRoute,
  StaffFinanceiroRoute: StaffFinanceiroRoute,
  StaffOnibusRoute: StaffOnibusRoute,
  StaffPassageirosRoute: StaffPassageirosRoute,
  StaffPerfilRoute: StaffPerfilRoute,
  StaffSuporteRoute: StaffSuporteRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffPassageiroIdRoute: StaffPassageiroIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ExcursionistaRoute: ExcursionistaRouteWithChildren,
  PassageiroRoute: PassageiroRouteWithChildren,
  SelecionarPerfilRoute: SelecionarPerfilRoute,
  StaffRoute: StaffRouteWithChildren,
  InvitePassageiroTokenRoute: InvitePassageiroTokenRoute,
  InviteStaffTokenRoute: InviteStaffTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
