/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SelecionarPerfilRouteImport } from './routes/selecionar-perfil'
import { Route as PassageiroRouteImport } from './routes/passageiro'
import { Route as ExcursionistaRouteImport } from './routes/excursionista'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as PassageiroIndexRouteImport } from './routes/passageiro.index'
import { Route as ExcursionistaIndexRouteImport } from './routes/excursionista.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as StaffSuporteRouteImport } from './routes/staff.suporte'
import { Route as StaffPassageirosRouteImport } from './routes/staff.passageiros'
import { Route as StaffOnibusRouteImport } from './routes/staff.onibus'
import { Route as StaffMensagensRouteImport } from './routes/staff.mensagens'
import { Route as StaffFinanceiroRouteImport } from './routes/staff.financeiro'
import { Route as StaffEquipeRouteImport } from './routes/staff.equipe'
import { Route as StaffConfiguracoesRouteImport } from './routes/staff.configuracoes'
import { Route as StaffCheckinRouteImport } from './routes/staff.checkin'
import { Route as PassageiroTicketRouteImport } from './routes/passageiro.ticket'
import { Route as PassageiroSuporteRouteImport } from './routes/passageiro.suporte'
import { Route as PassageiroRegrasRouteImport } from './routes/passageiro.regras'
import { Route as PassageiroPerfilRouteImport } from './routes/passageiro.perfil'
import { Route as PassageiroPagamentosRouteImport } from './routes/passageiro.pagamentos'
import { Route as PassageiroInformacoesRouteImport } from './routes/passageiro.informacoes'
import { Route as PassageiroChatRouteImport } from './routes/passageiro.chat'
import { Route as ExcursionistaPassageirosRouteImport } from './routes/excursionista.passageiros'
import { Route as ExcursionistaInfoRouteImport } from './routes/excursionista.info'
import { Route as ExcursionistaFinanceiroRouteImport } from './routes/excursionista.financeiro'
import { Route as ExcursionistaEditarRouteImport } from './routes/excursionista.editar'
import { Route as ExcursionistaCheckinRouteImport } from './routes/excursionista.checkin'
import { Route as ExcursionistaChatRouteImport } from './routes/excursionista.chat'
import { Route as StaffPassageiroIdRouteImport } from './routes/staff.passageiro.$id'
import { Route as PassageiroViagemIdRouteImport } from './routes/passageiro.viagem.$id'
import { Route as ExcursionistaExcursaoIdRouteImport } from './routes/excursionista.excursao.$id'
import { Route as AppExcursaoNovaRouteImport } from './routes/app.excursao.nova'
import { Route as AppExcursaoIdRouteImport } from './routes/app.excursao.$id'
import { Route as AppExcursaoIdIndexRouteImport } from './routes/app.excursao.$id.index'
import { Route as AppExcursaoIdPontosRouteImport } from './routes/app.excursao.$id.pontos'
import { Route as AppExcursaoIdPassageirosRouteImport } from './routes/app.excursao.$id.passageiros'
import { Route as AppExcursaoIdFinanceiroRouteImport } from './routes/app.excursao.$id.financeiro'
import { Route as AppExcursaoIdCheckinRouteImport } from './routes/app.excursao.$id.checkin'
import { Route as AppExcursaoIdChatRouteImport } from './routes/app.excursao.$id.chat'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecionarPerfilRoute = SelecionarPerfilRouteImport.update({
  id: '/selecionar-perfil',
  path: '/selecionar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroRoute = PassageiroRouteImport.update({
  id: '/passageiro',
  path: '/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcursionistaRoute = ExcursionistaRouteImport.update({
  id: '/excursionista',
  path: '/excursionista',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const PassageiroIndexRoute = PassageiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PassageiroRoute,
} as any)
const ExcursionistaIndexRoute = ExcursionistaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const StaffSuporteRoute = StaffSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPassageirosRoute = StaffPassageirosRouteImport.update({
  id: '/passageiros',
  path: '/passageiros',
  getParentRoute: () => StaffRoute,
} as any)
const StaffOnibusRoute = StaffOnibusRouteImport.update({
  id: '/onibus',
  path: '/onibus',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMensagensRoute = StaffMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFinanceiroRoute = StaffFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => StaffRoute,
} as any)
const StaffEquipeRoute = StaffEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => StaffRoute,
} as any)
const StaffConfiguracoesRoute = StaffConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCheckinRoute = StaffCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => StaffRoute,
} as any)
const PassageiroTicketRoute = PassageiroTicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroSuporteRoute = PassageiroSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroRegrasRoute = PassageiroRegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroPerfilRoute = PassageiroPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroPagamentosRoute = PassageiroPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroInformacoesRoute = PassageiroInformacoesRouteImport.update({
  id: '/informacoes',
  path: '/informacoes',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroChatRoute = PassageiroChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PassageiroRoute,
} as any)
const ExcursionistaPassageirosRoute =
  ExcursionistaPassageirosRouteImport.update({
    id: '/passageiros',
    path: '/passageiros',
    getParentRoute: () => ExcursionistaRoute,
  } as any)
const ExcursionistaInfoRoute = ExcursionistaInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const ExcursionistaFinanceiroRoute = ExcursionistaFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const ExcursionistaEditarRoute = ExcursionistaEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const ExcursionistaCheckinRoute = ExcursionistaCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const ExcursionistaChatRoute = ExcursionistaChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const StaffPassageiroIdRoute = StaffPassageiroIdRouteImport.update({
  id: '/passageiro/$id',
  path: '/passageiro/$id',
  getParentRoute: () => StaffRoute,
} as any)
const PassageiroViagemIdRoute = PassageiroViagemIdRouteImport.update({
  id: '/viagem/$id',
  path: '/viagem/$id',
  getParentRoute: () => PassageiroRoute,
} as any)
const ExcursionistaExcursaoIdRoute = ExcursionistaExcursaoIdRouteImport.update({
  id: '/excursao/$id',
  path: '/excursao/$id',
  getParentRoute: () => ExcursionistaRoute,
} as any)
const AppExcursaoNovaRoute = AppExcursaoNovaRouteImport.update({
  id: '/excursao/nova',
  path: '/excursao/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppExcursaoIdRoute = AppExcursaoIdRouteImport.update({
  id: '/excursao/$id',
  path: '/excursao/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppExcursaoIdIndexRoute = AppExcursaoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)
const AppExcursaoIdPontosRoute = AppExcursaoIdPontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)
const AppExcursaoIdPassageirosRoute =
  AppExcursaoIdPassageirosRouteImport.update({
    id: '/passageiros',
    path: '/passageiros',
    getParentRoute: () => AppExcursaoIdRoute,
  } as any)
const AppExcursaoIdFinanceiroRoute = AppExcursaoIdFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)
const AppExcursaoIdCheckinRoute = AppExcursaoIdCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)
const AppExcursaoIdChatRoute = AppExcursaoIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppExcursaoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/excursionista': typeof ExcursionistaRouteWithChildren
  '/passageiro': typeof PassageiroRouteWithChildren
  '/selecionar-perfil': typeof SelecionarPerfilRoute
  '/staff': typeof StaffRouteWithChildren
  '/excursionista/chat': typeof ExcursionistaChatRoute
  '/excursionista/checkin': typeof ExcursionistaCheckinRoute
  '/excursionista/editar': typeof ExcursionistaEditarRoute
  '/excursionista/financeiro': typeof ExcursionistaFinanceiroRoute
  '/excursionista/info': typeof ExcursionistaInfoRoute
  '/excursionista/passageiros': typeof ExcursionistaPassageirosRoute
  '/passageiro/chat': typeof PassageiroChatRoute
  '/passageiro/informacoes': typeof PassageiroInformacoesRoute
  '/passageiro/pagamentos': typeof PassageiroPagamentosRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/passageiro/regras': typeof PassageiroRegrasRoute
  '/passageiro/suporte': typeof PassageiroSuporteRoute
  '/passageiro/ticket': typeof PassageiroTicketRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/configuracoes': typeof StaffConfiguracoesRoute
  '/staff/equipe': typeof StaffEquipeRoute
  '/staff/financeiro': typeof StaffFinanceiroRoute
  '/staff/mensagens': typeof StaffMensagensRoute
  '/staff/onibus': typeof StaffOnibusRoute
  '/staff/passageiros': typeof StaffPassageirosRoute
  '/staff/suporte': typeof StaffSuporteRoute
  '/app/': typeof AppIndexRoute
  '/excursionista/': typeof ExcursionistaIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/app/excursao/$id': typeof AppExcursaoIdRouteWithChildren
  '/app/excursao/nova': typeof AppExcursaoNovaRoute
  '/excursionista/excursao/$id': typeof ExcursionistaExcursaoIdRoute
  '/passageiro/viagem/$id': typeof PassageiroViagemIdRoute
  '/staff/passageiro/$id': typeof StaffPassageiroIdRoute
  '/app/excursao/$id/chat': typeof AppExcursaoIdChatRoute
  '/app/excursao/$id/checkin': typeof AppExcursaoIdCheckinRoute
  '/app/excursao/$id/financeiro': typeof AppExcursaoIdFinanceiroRoute
  '/app/excursao/$id/passageiros': typeof AppExcursaoIdPassageirosRoute
  '/app/excursao/$id/pontos': typeof AppExcursaoIdPontosRoute
  '/app/excursao/$id/': typeof AppExcursaoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/selecionar-perfil': typeof SelecionarPerfilRoute
  '/excursionista/chat': typeof ExcursionistaChatRoute
  '/excursionista/checkin': typeof ExcursionistaCheckinRoute
  '/excursionista/editar': typeof ExcursionistaEditarRoute
  '/excursionista/financeiro': typeof ExcursionistaFinanceiroRoute
  '/excursionista/info': typeof ExcursionistaInfoRoute
  '/excursionista/passageiros': typeof ExcursionistaPassageirosRoute
  '/passageiro/chat': typeof PassageiroChatRoute
  '/passageiro/informacoes': typeof PassageiroInformacoesRoute
  '/passageiro/pagamentos': typeof PassageiroPagamentosRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/passageiro/regras': typeof PassageiroRegrasRoute
  '/passageiro/suporte': typeof PassageiroSuporteRoute
  '/passageiro/ticket': typeof PassageiroTicketRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/configuracoes': typeof StaffConfiguracoesRoute
  '/staff/equipe': typeof StaffEquipeRoute
  '/staff/financeiro': typeof StaffFinanceiroRoute
  '/staff/mensagens': typeof StaffMensagensRoute
  '/staff/onibus': typeof StaffOnibusRoute
  '/staff/passageiros': typeof StaffPassageirosRoute
  '/staff/suporte': typeof StaffSuporteRoute
  '/app': typeof AppIndexRoute
  '/excursionista': typeof ExcursionistaIndexRoute
  '/passageiro': typeof PassageiroIndexRoute
  '/staff': typeof StaffIndexRoute
  '/app/excursao/nova': typeof AppExcursaoNovaRoute
  '/excursionista/excursao/$id': typeof ExcursionistaExcursaoIdRoute
  '/passageiro/viagem/$id': typeof PassageiroViagemIdRoute
  '/staff/passageiro/$id': typeof StaffPassageiroIdRoute
  '/app/excursao/$id/chat': typeof AppExcursaoIdChatRoute
  '/app/excursao/$id/checkin': typeof AppExcursaoIdCheckinRoute
  '/app/excursao/$id/financeiro': typeof AppExcursaoIdFinanceiroRoute
  '/app/excursao/$id/passageiros': typeof AppExcursaoIdPassageirosRoute
  '/app/excursao/$id/pontos': typeof AppExcursaoIdPontosRoute
  '/app/excursao/$id': typeof AppExcursaoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/excursionista': typeof ExcursionistaRouteWithChildren
  '/passageiro': typeof PassageiroRouteWithChildren
  '/selecionar-perfil': typeof SelecionarPerfilRoute
  '/staff': typeof StaffRouteWithChildren
  '/excursionista/chat': typeof ExcursionistaChatRoute
  '/excursionista/checkin': typeof ExcursionistaCheckinRoute
  '/excursionista/editar': typeof ExcursionistaEditarRoute
  '/excursionista/financeiro': typeof ExcursionistaFinanceiroRoute
  '/excursionista/info': typeof ExcursionistaInfoRoute
  '/excursionista/passageiros': typeof ExcursionistaPassageirosRoute
  '/passageiro/chat': typeof PassageiroChatRoute
  '/passageiro/informacoes': typeof PassageiroInformacoesRoute
  '/passageiro/pagamentos': typeof PassageiroPagamentosRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/passageiro/regras': typeof PassageiroRegrasRoute
  '/passageiro/suporte': typeof PassageiroSuporteRoute
  '/passageiro/ticket': typeof PassageiroTicketRoute
  '/staff/checkin': typeof StaffCheckinRoute
  '/staff/configuracoes': typeof StaffConfiguracoesRoute
  '/staff/equipe': typeof StaffEquipeRoute
  '/staff/financeiro': typeof StaffFinanceiroRoute
  '/staff/mensagens': typeof StaffMensagensRoute
  '/staff/onibus': typeof StaffOnibusRoute
  '/staff/passageiros': typeof StaffPassageirosRoute
  '/staff/suporte': typeof StaffSuporteRoute
  '/app/': typeof AppIndexRoute
  '/excursionista/': typeof ExcursionistaIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/app/excursao/$id': typeof AppExcursaoIdRouteWithChildren
  '/app/excursao/nova': typeof AppExcursaoNovaRoute
  '/excursionista/excursao/$id': typeof ExcursionistaExcursaoIdRoute
  '/passageiro/viagem/$id': typeof PassageiroViagemIdRoute
  '/staff/passageiro/$id': typeof StaffPassageiroIdRoute
  '/app/excursao/$id/chat': typeof AppExcursaoIdChatRoute
  '/app/excursao/$id/checkin': typeof AppExcursaoIdCheckinRoute
  '/app/excursao/$id/financeiro': typeof AppExcursaoIdFinanceiroRoute
  '/app/excursao/$id/passageiros': typeof AppExcursaoIdPassageirosRoute
  '/app/excursao/$id/pontos': typeof AppExcursaoIdPontosRoute
  '/app/excursao/$id/': typeof AppExcursaoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/excursionista'
    | '/passageiro'
    | '/selecionar-perfil'
    | '/staff'
    | '/excursionista/chat'
    | '/excursionista/checkin'
    | '/excursionista/editar'
    | '/excursionista/financeiro'
    | '/excursionista/info'
    | '/excursionista/passageiros'
    | '/passageiro/chat'
    | '/passageiro/informacoes'
    | '/passageiro/pagamentos'
    | '/passageiro/perfil'
    | '/passageiro/regras'
    | '/passageiro/suporte'
    | '/passageiro/ticket'
    | '/staff/checkin'
    | '/staff/configuracoes'
    | '/staff/equipe'
    | '/staff/financeiro'
    | '/staff/mensagens'
    | '/staff/onibus'
    | '/staff/passageiros'
    | '/staff/suporte'
    | '/app/'
    | '/excursionista/'
    | '/passageiro/'
    | '/staff/'
    | '/app/excursao/$id'
    | '/app/excursao/nova'
    | '/excursionista/excursao/$id'
    | '/passageiro/viagem/$id'
    | '/staff/passageiro/$id'
    | '/app/excursao/$id/chat'
    | '/app/excursao/$id/checkin'
    | '/app/excursao/$id/financeiro'
    | '/app/excursao/$id/passageiros'
    | '/app/excursao/$id/pontos'
    | '/app/excursao/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/selecionar-perfil'
    | '/excursionista/chat'
    | '/excursionista/checkin'
    | '/excursionista/editar'
    | '/excursionista/financeiro'
    | '/excursionista/info'
    | '/excursionista/passageiros'
    | '/passageiro/chat'
    | '/passageiro/informacoes'
    | '/passageiro/pagamentos'
    | '/passageiro/perfil'
    | '/passageiro/regras'
    | '/passageiro/suporte'
    | '/passageiro/ticket'
    | '/staff/checkin'
    | '/staff/configuracoes'
    | '/staff/equipe'
    | '/staff/financeiro'
    | '/staff/mensagens'
    | '/staff/onibus'
    | '/staff/passageiros'
    | '/staff/suporte'
    | '/app'
    | '/excursionista'
    | '/passageiro'
    | '/staff'
    | '/app/excursao/nova'
    | '/excursionista/excursao/$id'
    | '/passageiro/viagem/$id'
    | '/staff/passageiro/$id'
    | '/app/excursao/$id/chat'
    | '/app/excursao/$id/checkin'
    | '/app/excursao/$id/financeiro'
    | '/app/excursao/$id/passageiros'
    | '/app/excursao/$id/pontos'
    | '/app/excursao/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/excursionista'
    | '/passageiro'
    | '/selecionar-perfil'
    | '/staff'
    | '/excursionista/chat'
    | '/excursionista/checkin'
    | '/excursionista/editar'
    | '/excursionista/financeiro'
    | '/excursionista/info'
    | '/excursionista/passageiros'
    | '/passageiro/chat'
    | '/passageiro/informacoes'
    | '/passageiro/pagamentos'
    | '/passageiro/perfil'
    | '/passageiro/regras'
    | '/passageiro/suporte'
    | '/passageiro/ticket'
    | '/staff/checkin'
    | '/staff/configuracoes'
    | '/staff/equipe'
    | '/staff/financeiro'
    | '/staff/mensagens'
    | '/staff/onibus'
    | '/staff/passageiros'
    | '/staff/suporte'
    | '/app/'
    | '/excursionista/'
    | '/passageiro/'
    | '/staff/'
    | '/app/excursao/$id'
    | '/app/excursao/nova'
    | '/excursionista/excursao/$id'
    | '/passageiro/viagem/$id'
    | '/staff/passageiro/$id'
    | '/app/excursao/$id/chat'
    | '/app/excursao/$id/checkin'
    | '/app/excursao/$id/financeiro'
    | '/app/excursao/$id/passageiros'
    | '/app/excursao/$id/pontos'
    | '/app/excursao/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExcursionistaRoute: typeof ExcursionistaRouteWithChildren
  PassageiroRoute: typeof PassageiroRouteWithChildren
  SelecionarPerfilRoute: typeof SelecionarPerfilRoute
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecionar-perfil': {
      id: '/selecionar-perfil'
      path: '/selecionar-perfil'
      fullPath: '/selecionar-perfil'
      preLoaderRoute: typeof SelecionarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro': {
      id: '/passageiro'
      path: '/passageiro'
      fullPath: '/passageiro'
      preLoaderRoute: typeof PassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excursionista': {
      id: '/excursionista'
      path: '/excursionista'
      fullPath: '/excursionista'
      preLoaderRoute: typeof ExcursionistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/passageiro/': {
      id: '/passageiro/'
      path: '/'
      fullPath: '/passageiro/'
      preLoaderRoute: typeof PassageiroIndexRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/excursionista/': {
      id: '/excursionista/'
      path: '/'
      fullPath: '/excursionista/'
      preLoaderRoute: typeof ExcursionistaIndexRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/staff/suporte': {
      id: '/staff/suporte'
      path: '/suporte'
      fullPath: '/staff/suporte'
      preLoaderRoute: typeof StaffSuporteRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/passageiros': {
      id: '/staff/passageiros'
      path: '/passageiros'
      fullPath: '/staff/passageiros'
      preLoaderRoute: typeof StaffPassageirosRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/onibus': {
      id: '/staff/onibus'
      path: '/onibus'
      fullPath: '/staff/onibus'
      preLoaderRoute: typeof StaffOnibusRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/mensagens': {
      id: '/staff/mensagens'
      path: '/mensagens'
      fullPath: '/staff/mensagens'
      preLoaderRoute: typeof StaffMensagensRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/financeiro': {
      id: '/staff/financeiro'
      path: '/financeiro'
      fullPath: '/staff/financeiro'
      preLoaderRoute: typeof StaffFinanceiroRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/equipe': {
      id: '/staff/equipe'
      path: '/equipe'
      fullPath: '/staff/equipe'
      preLoaderRoute: typeof StaffEquipeRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/configuracoes': {
      id: '/staff/configuracoes'
      path: '/configuracoes'
      fullPath: '/staff/configuracoes'
      preLoaderRoute: typeof StaffConfiguracoesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/checkin': {
      id: '/staff/checkin'
      path: '/checkin'
      fullPath: '/staff/checkin'
      preLoaderRoute: typeof StaffCheckinRouteImport
      parentRoute: typeof StaffRoute
    }
    '/passageiro/ticket': {
      id: '/passageiro/ticket'
      path: '/ticket'
      fullPath: '/passageiro/ticket'
      preLoaderRoute: typeof PassageiroTicketRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/suporte': {
      id: '/passageiro/suporte'
      path: '/suporte'
      fullPath: '/passageiro/suporte'
      preLoaderRoute: typeof PassageiroSuporteRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/regras': {
      id: '/passageiro/regras'
      path: '/regras'
      fullPath: '/passageiro/regras'
      preLoaderRoute: typeof PassageiroRegrasRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/perfil': {
      id: '/passageiro/perfil'
      path: '/perfil'
      fullPath: '/passageiro/perfil'
      preLoaderRoute: typeof PassageiroPerfilRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/pagamentos': {
      id: '/passageiro/pagamentos'
      path: '/pagamentos'
      fullPath: '/passageiro/pagamentos'
      preLoaderRoute: typeof PassageiroPagamentosRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/informacoes': {
      id: '/passageiro/informacoes'
      path: '/informacoes'
      fullPath: '/passageiro/informacoes'
      preLoaderRoute: typeof PassageiroInformacoesRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/chat': {
      id: '/passageiro/chat'
      path: '/chat'
      fullPath: '/passageiro/chat'
      preLoaderRoute: typeof PassageiroChatRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/excursionista/passageiros': {
      id: '/excursionista/passageiros'
      path: '/passageiros'
      fullPath: '/excursionista/passageiros'
      preLoaderRoute: typeof ExcursionistaPassageirosRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/excursionista/info': {
      id: '/excursionista/info'
      path: '/info'
      fullPath: '/excursionista/info'
      preLoaderRoute: typeof ExcursionistaInfoRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/excursionista/financeiro': {
      id: '/excursionista/financeiro'
      path: '/financeiro'
      fullPath: '/excursionista/financeiro'
      preLoaderRoute: typeof ExcursionistaFinanceiroRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/excursionista/editar': {
      id: '/excursionista/editar'
      path: '/editar'
      fullPath: '/excursionista/editar'
      preLoaderRoute: typeof ExcursionistaEditarRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/excursionista/checkin': {
      id: '/excursionista/checkin'
      path: '/checkin'
      fullPath: '/excursionista/checkin'
      preLoaderRoute: typeof ExcursionistaCheckinRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/excursionista/chat': {
      id: '/excursionista/chat'
      path: '/chat'
      fullPath: '/excursionista/chat'
      preLoaderRoute: typeof ExcursionistaChatRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/staff/passageiro/$id': {
      id: '/staff/passageiro/$id'
      path: '/passageiro/$id'
      fullPath: '/staff/passageiro/$id'
      preLoaderRoute: typeof StaffPassageiroIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/passageiro/viagem/$id': {
      id: '/passageiro/viagem/$id'
      path: '/viagem/$id'
      fullPath: '/passageiro/viagem/$id'
      preLoaderRoute: typeof PassageiroViagemIdRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/excursionista/excursao/$id': {
      id: '/excursionista/excursao/$id'
      path: '/excursao/$id'
      fullPath: '/excursionista/excursao/$id'
      preLoaderRoute: typeof ExcursionistaExcursaoIdRouteImport
      parentRoute: typeof ExcursionistaRoute
    }
    '/app/excursao/nova': {
      id: '/app/excursao/nova'
      path: '/excursao/nova'
      fullPath: '/app/excursao/nova'
      preLoaderRoute: typeof AppExcursaoNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/excursao/$id': {
      id: '/app/excursao/$id'
      path: '/excursao/$id'
      fullPath: '/app/excursao/$id'
      preLoaderRoute: typeof AppExcursaoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/excursao/$id/': {
      id: '/app/excursao/$id/'
      path: '/'
      fullPath: '/app/excursao/$id/'
      preLoaderRoute: typeof AppExcursaoIdIndexRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/pontos': {
      id: '/app/excursao/$id/pontos'
      path: '/pontos'
      fullPath: '/app/excursao/$id/pontos'
      preLoaderRoute: typeof AppExcursaoIdPontosRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/passageiros': {
      id: '/app/excursao/$id/passageiros'
      path: '/passageiros'
      fullPath: '/app/excursao/$id/passageiros'
      preLoaderRoute: typeof AppExcursaoIdPassageirosRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/financeiro': {
      id: '/app/excursao/$id/financeiro'
      path: '/financeiro'
      fullPath: '/app/excursao/$id/financeiro'
      preLoaderRoute: typeof AppExcursaoIdFinanceiroRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/checkin': {
      id: '/app/excursao/$id/checkin'
      path: '/checkin'
      fullPath: '/app/excursao/$id/checkin'
      preLoaderRoute: typeof AppExcursaoIdCheckinRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
    '/app/excursao/$id/chat': {
      id: '/app/excursao/$id/chat'
      path: '/chat'
      fullPath: '/app/excursao/$id/chat'
      preLoaderRoute: typeof AppExcursaoIdChatRouteImport
      parentRoute: typeof AppExcursaoIdRoute
    }
  }
}

interface AppExcursaoIdRouteChildren {
  AppExcursaoIdChatRoute: typeof AppExcursaoIdChatRoute
  AppExcursaoIdCheckinRoute: typeof AppExcursaoIdCheckinRoute
  AppExcursaoIdFinanceiroRoute: typeof AppExcursaoIdFinanceiroRoute
  AppExcursaoIdPassageirosRoute: typeof AppExcursaoIdPassageirosRoute
  AppExcursaoIdPontosRoute: typeof AppExcursaoIdPontosRoute
  AppExcursaoIdIndexRoute: typeof AppExcursaoIdIndexRoute
}

const AppExcursaoIdRouteChildren: AppExcursaoIdRouteChildren = {
  AppExcursaoIdChatRoute: AppExcursaoIdChatRoute,
  AppExcursaoIdCheckinRoute: AppExcursaoIdCheckinRoute,
  AppExcursaoIdFinanceiroRoute: AppExcursaoIdFinanceiroRoute,
  AppExcursaoIdPassageirosRoute: AppExcursaoIdPassageirosRoute,
  AppExcursaoIdPontosRoute: AppExcursaoIdPontosRoute,
  AppExcursaoIdIndexRoute: AppExcursaoIdIndexRoute,
}

const AppExcursaoIdRouteWithChildren = AppExcursaoIdRoute._addFileChildren(
  AppExcursaoIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppExcursaoIdRoute: typeof AppExcursaoIdRouteWithChildren
  AppExcursaoNovaRoute: typeof AppExcursaoNovaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppExcursaoIdRoute: AppExcursaoIdRouteWithChildren,
  AppExcursaoNovaRoute: AppExcursaoNovaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ExcursionistaRouteChildren {
  ExcursionistaChatRoute: typeof ExcursionistaChatRoute
  ExcursionistaCheckinRoute: typeof ExcursionistaCheckinRoute
  ExcursionistaEditarRoute: typeof ExcursionistaEditarRoute
  ExcursionistaFinanceiroRoute: typeof ExcursionistaFinanceiroRoute
  ExcursionistaInfoRoute: typeof ExcursionistaInfoRoute
  ExcursionistaPassageirosRoute: typeof ExcursionistaPassageirosRoute
  ExcursionistaIndexRoute: typeof ExcursionistaIndexRoute
  ExcursionistaExcursaoIdRoute: typeof ExcursionistaExcursaoIdRoute
}

const ExcursionistaRouteChildren: ExcursionistaRouteChildren = {
  ExcursionistaChatRoute: ExcursionistaChatRoute,
  ExcursionistaCheckinRoute: ExcursionistaCheckinRoute,
  ExcursionistaEditarRoute: ExcursionistaEditarRoute,
  ExcursionistaFinanceiroRoute: ExcursionistaFinanceiroRoute,
  ExcursionistaInfoRoute: ExcursionistaInfoRoute,
  ExcursionistaPassageirosRoute: ExcursionistaPassageirosRoute,
  ExcursionistaIndexRoute: ExcursionistaIndexRoute,
  ExcursionistaExcursaoIdRoute: ExcursionistaExcursaoIdRoute,
}

const ExcursionistaRouteWithChildren = ExcursionistaRoute._addFileChildren(
  ExcursionistaRouteChildren,
)

interface PassageiroRouteChildren {
  PassageiroChatRoute: typeof PassageiroChatRoute
  PassageiroInformacoesRoute: typeof PassageiroInformacoesRoute
  PassageiroPagamentosRoute: typeof PassageiroPagamentosRoute
  PassageiroPerfilRoute: typeof PassageiroPerfilRoute
  PassageiroRegrasRoute: typeof PassageiroRegrasRoute
  PassageiroSuporteRoute: typeof PassageiroSuporteRoute
  PassageiroTicketRoute: typeof PassageiroTicketRoute
  PassageiroIndexRoute: typeof PassageiroIndexRoute
  PassageiroViagemIdRoute: typeof PassageiroViagemIdRoute
}

const PassageiroRouteChildren: PassageiroRouteChildren = {
  PassageiroChatRoute: PassageiroChatRoute,
  PassageiroInformacoesRoute: PassageiroInformacoesRoute,
  PassageiroPagamentosRoute: PassageiroPagamentosRoute,
  PassageiroPerfilRoute: PassageiroPerfilRoute,
  PassageiroRegrasRoute: PassageiroRegrasRoute,
  PassageiroSuporteRoute: PassageiroSuporteRoute,
  PassageiroTicketRoute: PassageiroTicketRoute,
  PassageiroIndexRoute: PassageiroIndexRoute,
  PassageiroViagemIdRoute: PassageiroViagemIdRoute,
}

const PassageiroRouteWithChildren = PassageiroRoute._addFileChildren(
  PassageiroRouteChildren,
)

interface StaffRouteChildren {
  StaffCheckinRoute: typeof StaffCheckinRoute
  StaffConfiguracoesRoute: typeof StaffConfiguracoesRoute
  StaffEquipeRoute: typeof StaffEquipeRoute
  StaffFinanceiroRoute: typeof StaffFinanceiroRoute
  StaffMensagensRoute: typeof StaffMensagensRoute
  StaffOnibusRoute: typeof StaffOnibusRoute
  StaffPassageirosRoute: typeof StaffPassageirosRoute
  StaffSuporteRoute: typeof StaffSuporteRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffPassageiroIdRoute: typeof StaffPassageiroIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCheckinRoute: StaffCheckinRoute,
  StaffConfiguracoesRoute: StaffConfiguracoesRoute,
  StaffEquipeRoute: StaffEquipeRoute,
  StaffFinanceiroRoute: StaffFinanceiroRoute,
  StaffMensagensRoute: StaffMensagensRoute,
  StaffOnibusRoute: StaffOnibusRoute,
  StaffPassageirosRoute: StaffPassageirosRoute,
  StaffSuporteRoute: StaffSuporteRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffPassageiroIdRoute: StaffPassageiroIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ExcursionistaRoute: ExcursionistaRouteWithChildren,
  PassageiroRoute: PassageiroRouteWithChildren,
  SelecionarPerfilRoute: SelecionarPerfilRoute,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
